### ISSUE TITLE
Practica 4 Animación de objeto 3d en Blender

### ISSUE THREAD

**Issue by AdrianGonzalez-17** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-damaris#1]
[REPORTE PRACTICA 4 ANIMACIÓN DE OBJETO 3D EN BLENDER.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo-damaris/files/8347433/REPORTE.PRACTICA.4.ANIMACION.DE.OBJETO.3D.EN.BLENDER.pdf)

**Comment by claudiasilvavenda** [comment]
La calificación  19 %
falto subir la animación a Heroku

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
